import esbuild from "esbuild";
import { copyFileSync } from "node:fs";
import { builtinModules } from "node:module";

const production = process.argv.includes("production");
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const external = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtinModules,
  ...builtinModules.map((moduleName) => `node:${moduleName}`)
];

await esbuild.build({
  banner: {
    js: banner
  },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external,
  format: "cjs",
  logLevel: "info",
  minify: production,
  outfile: "main.js",
  platform: "browser",
  sourcemap: production ? false : "inline",
  target: "es2018",
  treeShaking: true
});

copyFileSync("src/view/styles.css", "styles.css");

